- question: Яка з наведених характеристик не є характеристикою інформаційної гігієни?
  answers:
    - Вона є новою історичною фазою розвитку суспільства
    - Вона включає в себе вплив на організм людини та суспільне здоров'я інформаційних потоків, що надходять до людини
    - Вона є системою, призначеною для одержання, обробки, зберігання, відображення та/або реєстрації даних
  correct: Вона є новою історичною фазою розвитку суспільства