- question: Що включає в себе поняття "інформаційна гігієна"?
  answers:
    - Вплив на організм людини та суспільне здоров'я інформаційних потоків, що надходять до людини.
    - Система, призначена для одержання, обробки, зберігання, відображення та/або реєстрації даних
    - Нову історичну фазу розвитку суспільства
  correct: Вплив на організм людини та суспільне здоров'я інформаційних потоків, що надходять до людини.
