en:
  greeting_message: "Hi! Let's start!"
  farewell_message: "Bye! See you soon"
  unknown_command: "Unknown command. Try again."
  user_name: "User name"
  start_time: "Start time"
  question: "Question"
  your_answer: "Your answer"
  correct_answer: "Correct answer"
  right: "Correct!"
  wrong: "Incorrect!"
  enter_answer_number: "Enter the answer number (1-%{count}):"
  invalid_answer_number: "Enter a valid answer number."
  test_summary: "Test summary:"
  correct_answers: "Correct answers"
  incorrect_answers: "Incorrect answers"
  total_questions: "Total questions"
  correct_percent: "Correct answers percent"
  start_test: "Start test"
  test_finished: "Test finished! Correct answers: %{correct}/%{total}"
  show_stats: "Statistics"
  test_finished_stats: "Test finished!\nCorrect: %{correct}\nIncorrect: %{incorrect}\nPercent: %{percent}%%"
  your_stats: "Your statistics:\nCorrect: %{correct}\nIncorrect: %{incorrect}\nPercent: %{percent}%%"
  no_stats: "No statistics available."
ua:
  greeting_message: "Привіт! Почнемо роботу!"
  farewell_message: "Прощавай! До зустрічі"
  unknown_command: "Невідома команда. Спробуйте ще раз."
  enter_name: "Введіть ваше ім'я:"
  empty_name: "Ім'я не може бути порожнім."
  user_name: "Ім'я користувача"
  start_time: "Час початку"
  question: "Питання"
  your_answer: "Ваша відповідь"
  correct_answer: "Правильна відповідь"
  right: "Вірно!"
  wrong: "Невірно!"
  enter_answer_number: "Введіть номер відповіді (1-%{count}):"
  invalid_answer_number: "Введіть коректний номер відповіді."
  test_summary: "Підсумки тесту:"
  correct_answers: "Коректних відповідей"
  incorrect_answers: "Некоректних відповідей"
  total_questions: "Всього питань"
  correct_percent: "Відсоток коректних відповідей"
  start_test: "Почати тест"
  test_finished: "Тест завершено! Вірних відповідей: %{correct}/%{total}"
  show_stats: "Статистика"
  test_finished_stats: "Тест завершено!\nПравильних: %{correct}\nНеправильних: %{incorrect}\nВідсоток: %{percent}%%"
  your_stats: "Ваша статистика:\nПравильних: %{correct}\nНеправильних: %{incorrect}\nВідсоток: %{percent}%%"
  no_stats: "Статистика відсутня."